# Generated by Django 5.2 on 2026-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.IntegerField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=15)),
                ('score_eligibilite', models.IntegerField(default=0, editable=False)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15)),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
    ]
