# Generated by Django 5.2 on 2026-06-15 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['AGENT', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traités', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='echeance',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.demandecredit'),
        ),
    ]
