# Generated by Django 5.2 on 2026-06-15 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecredit',
            name='date_soumission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
