# Generated by Django 5.2 on 2026-06-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_demandecredit_date_soumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='interets_totaux',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='echeance',
            name='jours_retard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='echeance',
            name='penalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
