# Generated by Django 5.2 on 2026-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couverture', models.TextField()),
            ],
            options={
                'ordering': ['prix_mensuel'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée')], default='ACTIVE', max_length=10)),
                ('notif_envoyee', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
