# Generated by Django 5.2 on 2026-06-15 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assurances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='souscription',
            name='formule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='assurances.formuleassurance'),
        ),
    ]
